# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('str1', models.CharField(max_length=64)),
                ('str2', models.CharField(max_length=128)),
                ('str3', models.DateTimeField(max_length=48)),
            ],
            options={
                'db_table': 'emailtype',
            },
        ),
    ]
