# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-27 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailtype',
        ),
    ]
